---
name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
      - uses: fish-shop/install-fish-shell@v1
      - run: pre-commit try-repo . fish_syntax --verbose --all-files
      - run: pre-commit try-repo . fish_indent --verbose --all-files
